// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WebToolCallResult } from "./WebToolCallResult";

export type WebChatMessage = { id: string, role: string, content: string, reasoning?: string, tools?: Array<WebToolCallResult>, };
