// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WebMemoryItem = { topic: string, content: string, tags?: string, updated_at: string, };
